version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_lab4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_web_lab4
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_pass
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=fastapi_db
    depends_on:
      - db

volumes:
  postgres_data:
